<?php
    $n=$_POST["name"];
    $fn=$_POST["fathername"];
    $mn=$_POST["mothername"];
    $dob=$_POST["dateofbirth"];
    $age=$_POST["age"];
    $email=$_POST["email"];
    $m=$_POST["mobileno"];
    $g=$_POST["gender"];
    $ad=$_POST["address"];
    $pn=$_POST["pincode"];
    $c=$_POST["city"];
    $s=$_POST["state"];
    echo "<center><h1>your form submitted successfully</h1></center>";
    echo"<br>";
    echo"<h2>your details</h2>";
    echo"<br>";
    echo"Name :";
    echo"$n";
    echo"<br><br>";
    echo"Father name:";
    echo"$fn";
    echo"<br><br>";
    echo"Mother name:";
    echo"$mn";
    echo"<br><br>";
    echo"Age";
    echo"$age";
    echo"<br><br>";
    echo"Dateofbirth:";
    echo"$dob";
    echo"<br><br>";
    echo"email:  ";
    echo"$email";
    echo"<br><br>";
    echo"Mobileno :";
    echo"$m";
    echo"<br><br>";
    echo"Gender :";
    echo"$g";
    echo"<br><br>";
    echo"Address :";
    echo"$ad";
    echo"<br><br>";
    echo"Pincode :";
    echo"$pn";
    echo"<br><br>";
    echo"City :";
    echo"$c";
    echo"<br><br>";
    echo"State :";
    echo"$s";
    echo"<br>";
?>
